### ISSUE TITLE
Unsupported Image Type for certain JPEG files

### ISSUE THREAD

**Issue by apandichi** [bertramdev/selfie#22]
When I try to save an Attachment for a particular JPEG file, it fails with the following exception:

`Caused by: javax.imageio.IIOException: Unsupported Image Type
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1068)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:1039)
	at javax.imageio.ImageIO.read(ImageIO.java:1448)
	at javax.imageio.ImageIO.read(ImageIO.java:1352)
	at com.bertramlabs.plugins.selfie.processors.ImageResizer.process(ImageResizer.groovy:22)
	at com.bertramlabs.plugins.selfie.Attachment.reprocessStyles(Attachment.groovy:221)
	at com.bertramlabs.plugins.selfie.Attachment.save(Attachment.groovy:160)
	at com.bertramlabs.plugins.selfie.PersistenceEventListener.preSave(PersistenceEventListener.groovy:86)
	at com.bertramlabs.plugins.selfie.PersistenceEventListener.onPersistenceEvent(PersistenceEventListener.groovy:28)
`

Reading around StackOverflow, I noticed that "ImageIO can't read CMYK-encoded jpeg images" (see [here](https://stackoverflow.com/questions/7177655/java-imageio-iioexception-unsupported-image-type) for example). Shouldn't `selfie` accept these images as well? They're valid images after all.

Thanks!

P.S. Awesome Grails plugin though, much appreciated.

**Comment by apandichi** [comment]
Maybe this can be of help?
https://stackoverflow.com/a/16149142/3177496

**Comment by davydotcom** [comment]
Great to hear
